name: Update packages

on:
  workflow_dispatch:
  schedule:
  # Every day at 4am
  - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Checkout AutoEQ
        uses: actions/checkout@v5
        with:
          repository: jaakkopasanen/AutoEq
          path: autoeq/

      - name: Get latest release info
        run:
          curl -fLO https://github.com/timschneeb/AutoEqPackages/releases/latest/download/version.json || true

      - name: Run packaging script
        run: |
          cd autoeq
          python ../package.py

      - name: Check file existence
        run: |
          test -e autoeq/archive.tar.gz
          test -e autoeq/export/index.json
          test -e autoeq/export/version.json

      - name: Collect exported data
        run: |
          mv autoeq/archive.tar.gz .
          mv autoeq/export/index.json .
          mv autoeq/export/version.json .
          rm -rf autoeq

      - name: Create tag
        id: create-tag
        run: |
          TAG="autoeq-$(date -uI)"
          echo "tag-name=${TAG}" >> "${GITHUB_OUTPUT}"
          git tag "${TAG}"
          git push --tags

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create-tag.outputs.tag-name }}
          files: |
            archive.tar.gz
            index.json
            version.json
